/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class memprof_memprof */

#ifndef _Included_memprof_memprof
#define _Included_memprof_memprof
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     memprof_memprof
 * Method:    _dumpHeap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_memprof_memprof__1dumpHeap
  (JNIEnv *, jclass, jstring);

/*
 * Class:     memprof_memprof
 * Method:    _dumpOnShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_memprof_memprof__1dumpOnShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class memprof_memprof_CommandLineOptions */

#ifndef _Included_memprof_memprof_CommandLineOptions
#define _Included_memprof_memprof_CommandLineOptions
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
