/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jist_swans_misc_Util */

#ifndef _Included_jist_swans_misc_Util
#define _Included_jist_swans_misc_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jist_swans_misc_Util
 * Method:    fast_log
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_jist_swans_misc_Util_fast_1log
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
